### PR TITLE
chore(yarn): replace solium with ethlint

### PR DESCRIPTION
**Pull request by 0xferit**
Solium is discontinued. Doesn't work with Solidity 0.5

### CODE REVIEW

**Comment by satello** [comment]
👍

**Review by satello — DISMISSED** [review]

**Comment by 0xferit** [comment]
We still can't merge :) @clesaege  Can you please remove merge restriction which only lets admins to merge?

**Comment by 0xferit** [comment]
@satello

**Review by satello — APPROVED** [review]

**Comment by satello** [comment]
Merge at will. Sorry I gave you the thumbs up but not the official approval @ferittuncer

**Pull request merged**
